apiVersion: apps/v1
kind: Deployment
metadata:
  name: abe-csi-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abe-csi-controller
  template:
    metadata:
      labels:
        app: abe-csi-controller
    spec:
      serviceAccountName: csi-controller-sa
      containers:
      - name: abe-csi
        image: briankmatheson/abe:latest
        args:
        - "--endpoint=unix:///csi/csi.sock"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: csi-provisioner
        image: registry.k8s.io/sig-storage/csi-provisioner:v5.0.1
        args:
        - "--csi-address=tcp://127.0.0.1:50051"
        - "--v=5"
        - "--timeout=60s"
        - "--feature-gates=Topology=true"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: csi-attacher
        image: registry.k8s.io/sig-storage/csi-attacher:v4.4.1
        args:
        - "--csi-address=tcp://127.0.0.1:50051"
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      volumes:
      - name: socket-dir
        emptyDir: {}
