apiVersion: v1
kind: ServiceAccount
metadata:
  name: abe-csi
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: abe-csi
rules:
- apiGroups: [""]
  resources: ["nodes", "events", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["csinodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: abe-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: abe-csi
subjects:
- kind: ServiceAccount
  name: abe-csi
  namespace: kube-system
