apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-controller-sa
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-node-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: abe-csi-provisioner-role
rules:
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims", "pods"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses", "csinodes", "csidrivers", "csistoragecapacities"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: abe-csi-provisioner-binding
roleRef:
  kind: ClusterRole
  name: abe-csi-provisioner-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: csi-controller-sa
  namespace: kube-system
