apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: abe-csi
provisioner: abe.csi.briankmatheson
parameters:
  HOSTS: brick,brick,brick
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
