apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: abe-csi
provisioner: abe.csi.briankmatheson
parameters:
  HOSTS: abe-a,abe-b,abe-c
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
