apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: abe-csi-sc
provisioner: abe.csi.briankmatheson
parameters:
  type: ssd
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
